### ISSUE TITLE
Is it really a compiler?

### ISSUE THREAD

**Issue by jhfhngj** [oXo23/Nex#5]
Close this if you want, but Python is interpreted, not compiled

**Comment by oXo23** [comment]
a s2s compiler usually translates a high-level language to a low-level, but my compiler is translating it from high-level to high-level, but still though, at NEX's core, if NEX detects that it can export itself on your OS (only windows supported for now), it well compiles itself to a .exe (because exporting is only supported on windows for now)

but that well be labeled as an enchant, because I am actually working on making it translate itself to C-lang (which is a low-level)

So, for now, we can say it's translated but not compiled till the next update which well have it being compiled to C.

**Comment by jhfhngj** [comment]
so nex to python to c to exe?
also whats that temp.nexC

**Comment by oXo23** [comment]
> so nex to python to c to exe? also whats that temp.nexC

the compiled python version of the nex script
